FROM python:3.14-slim@sha256:bc389f7dfcb21413e72a28f491985326994795e34d2b86c8ae2f417b4e7818aa

ARG NAME
ARG NLP_CONF_FILE=default

ENV PIPENV_VENV_IN_PROJECT=1
ENV PIP_NO_CACHE_DIR=1
ENV POETRY_VIRTUALENVS_CREATE=false
WORKDIR /app/

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY ./pyproject.toml /app/

RUN pip install poetry==2.3.2 waitress \
    && poetry install --no-root --only=main -E server \
    && rm -rf $(poetry config cache-dir)

COPY . /app/

RUN apt-get clean autoclean
RUN apt-get autoremove --yes
RUN rm -rf /var/lib/{apt,dpkg,cache,log}/

EXPOSE 5002

CMD ["waitress-serve", "--port=5002", "--call", "app:start"]
